spring.application.name=gmail-runner
gmail.app.name=meet-joiner
gmail.credentials.path=credentials.json
gmail.tokens.directory.path=./tokens
gmail.polling.query=is:unread meet.google.com
gmail.user.id=me

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
