package com.proj.llmsummaryservice.services;

import com.google.api.services.gmail.Gmail;
import com.google.api.services.gmail.model.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.Session;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.codec.binary.Base64;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.Properties;

@Slf4j
@Service
@RequiredArgsConstructor
public class EmailService {

    private final Gmail gmailService; // Inject the configured Gmail client from GmailConfig

    @Value("${google.gmail.user.id}")
    private String gmailUserId; // Configured user ID ('me')

    /**
     * Sends the meeting summary and transcript via email using the Gmail API.
     * The email is sent TO the specified recipient.
     *
     * @param recipientEmail The email address of the recipient.
     * @param meetingId      The unique ID of the meeting.
     * @param summary        The summary generated by the LLM.
     * @param fullTranscript The complete transcript of the meeting.
     */
    public void sendSummaryEmail(String recipientEmail, String meetingId, String summary, String fullTranscript) {
        log.info("Attempting to send summary email for meeting {} to {} via Gmail API", meetingId, recipientEmail);
        try {
            // 1. Create the email content, sending TO the specified recipientEmail
            MimeMessage mimeMessage = createMimeMessage(recipientEmail, meetingId, summary, fullTranscript);

            // 2. Convert the MimeMessage to a Gmail API Message
            Message message = createGmailMessage(mimeMessage);

            // 3. Send the email using the Gmail API
            // 'gmailUserId' is 'me', which means we are sending *as* the authenticated user
            gmailService.users().messages().send(gmailUserId, message).execute();

            log.info("Successfully sent summary email for meeting {} to {} via Gmail API", meetingId, recipientEmail);
        } catch (MessagingException | IOException e) {
            log.error("Failed to send summary email for meeting {} to {}: {}", meetingId, recipientEmail, e.getMessage(), e);
        } catch (Exception e) {
            // Catch broader exceptions from the Gmail API client
            log.error("An unexpected error occurred while sending Gmail for meeting {}: {}", meetingId, e.getMessage(), e);
        }
    }

    /**
     * Creates a MimeMessage object for the email content using Jakarta Mail API.
     */
    private MimeMessage createMimeMessage(String to, String meetingId, String summary, String transcript)
            throws MessagingException {
        Properties props = new Properties();
        Session session = Session.getDefaultInstance(props, null);
        MimeMessage email = new MimeMessage(session);

        // Set sender (will be overridden by Gmail API based on authenticated user)
        email.setFrom(new InternetAddress("me")); // Indicates the authenticated user
        email.addRecipient(jakarta.mail.Message.RecipientType.TO, new InternetAddress(to));
        email.setSubject("Meeting Summary & Transcript: " + meetingId);

        // Construct email body
        StringBuilder body = new StringBuilder();
        body.append("Meeting Summary for ID: ").append(meetingId).append("\n\n");
        body.append("================ SUMMARY ================\n");
        body.append(summary).append("\n\n");
        body.append("================ FULL TRANSCRIPT ================\n");
        // Limit transcript length if necessary
        int maxLength = 50000; // Example limit for email body size
        if (transcript.length() > maxLength) {
            body.append(transcript.substring(0, maxLength));
            body.append("\n\n... [Transcript truncated due to length]");
        } else {
            body.append(transcript);
        }

        email.setText(body.toString(), "UTF-8"); // Specify UTF-8 encoding
        return email;
    }

    /**
     * Creates a Gmail API Message object from a MimeMessage.
     * Encodes the email content to base64url format required by the API.
     */
    private Message createGmailMessage(MimeMessage mimeMessage) throws IOException, MessagingException {
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        mimeMessage.writeTo(buffer);
        byte[] rawMessageBytes = buffer.toByteArray();
        String encodedEmail = Base64.encodeBase64URLSafeString(rawMessageBytes);
        Message message = new Message();
        message.setRaw(encodedEmail);
        return message;
    }
}


